version: "3"
services:

  bankaccount:
    container_name: "bankaccount"
    restart: always
    build: .
    ports:
      - "8080:8080"

  mysqldb:
    container_name: "mysqldb"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bankaccount
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - bank_account_data:/etc/mysql/conf.d

volumes:
  bank_account_data: